# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lain/cs100/final-project-quaranteam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lain/cs100/final-project-quaranteam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lain/cs100/final-project-quaranteam/CMakeFiles /home/lain/cs100/final-project-quaranteam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lain/cs100/final-project-quaranteam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runUnitTest

# Build rule for target.
runUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runUnitTest
.PHONY : runUnitTest

# fast build rule for target.
runUnitTest/fast:
	$(MAKE) -f CMakeFiles/runUnitTest.dir/build.make CMakeFiles/runUnitTest.dir/build
.PHONY : runUnitTest/fast

#=============================================================================
# Target rules for targets named gameAsciiRpg

# Build rule for target.
gameAsciiRpg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameAsciiRpg
.PHONY : gameAsciiRpg

# fast build rule for target.
gameAsciiRpg/fast:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/build
.PHONY : gameAsciiRpg/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

BattleVisitor/BattleVisitor.o: BattleVisitor/BattleVisitor.cpp.o

.PHONY : BattleVisitor/BattleVisitor.o

# target to build an object file
BattleVisitor/BattleVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/BattleVisitor/BattleVisitor.cpp.o
.PHONY : BattleVisitor/BattleVisitor.cpp.o

BattleVisitor/BattleVisitor.i: BattleVisitor/BattleVisitor.cpp.i

.PHONY : BattleVisitor/BattleVisitor.i

# target to preprocess a source file
BattleVisitor/BattleVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/BattleVisitor/BattleVisitor.cpp.i
.PHONY : BattleVisitor/BattleVisitor.cpp.i

BattleVisitor/BattleVisitor.s: BattleVisitor/BattleVisitor.cpp.s

.PHONY : BattleVisitor/BattleVisitor.s

# target to generate assembly for a file
BattleVisitor/BattleVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/BattleVisitor/BattleVisitor.cpp.s
.PHONY : BattleVisitor/BattleVisitor.cpp.s

Character/Character.o: Character/Character.cpp.o

.PHONY : Character/Character.o

# target to build an object file
Character/Character.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Character/Character.cpp.o
.PHONY : Character/Character.cpp.o

Character/Character.i: Character/Character.cpp.i

.PHONY : Character/Character.i

# target to preprocess a source file
Character/Character.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Character/Character.cpp.i
.PHONY : Character/Character.cpp.i

Character/Character.s: Character/Character.cpp.s

.PHONY : Character/Character.s

# target to generate assembly for a file
Character/Character.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Character/Character.cpp.s
.PHONY : Character/Character.cpp.s

Equipment/src/Axe.o: Equipment/src/Axe.cpp.o

.PHONY : Equipment/src/Axe.o

# target to build an object file
Equipment/src/Axe.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Axe.cpp.o
.PHONY : Equipment/src/Axe.cpp.o

Equipment/src/Axe.i: Equipment/src/Axe.cpp.i

.PHONY : Equipment/src/Axe.i

# target to preprocess a source file
Equipment/src/Axe.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Axe.cpp.i
.PHONY : Equipment/src/Axe.cpp.i

Equipment/src/Axe.s: Equipment/src/Axe.cpp.s

.PHONY : Equipment/src/Axe.s

# target to generate assembly for a file
Equipment/src/Axe.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Axe.cpp.s
.PHONY : Equipment/src/Axe.cpp.s

Equipment/src/Deadly.o: Equipment/src/Deadly.cpp.o

.PHONY : Equipment/src/Deadly.o

# target to build an object file
Equipment/src/Deadly.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Deadly.cpp.o
.PHONY : Equipment/src/Deadly.cpp.o

Equipment/src/Deadly.i: Equipment/src/Deadly.cpp.i

.PHONY : Equipment/src/Deadly.i

# target to preprocess a source file
Equipment/src/Deadly.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Deadly.cpp.i
.PHONY : Equipment/src/Deadly.cpp.i

Equipment/src/Deadly.s: Equipment/src/Deadly.cpp.s

.PHONY : Equipment/src/Deadly.s

# target to generate assembly for a file
Equipment/src/Deadly.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Deadly.cpp.s
.PHONY : Equipment/src/Deadly.cpp.s

Equipment/src/EquipmentDecorator.o: Equipment/src/EquipmentDecorator.cpp.o

.PHONY : Equipment/src/EquipmentDecorator.o

# target to build an object file
Equipment/src/EquipmentDecorator.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/EquipmentDecorator.cpp.o
.PHONY : Equipment/src/EquipmentDecorator.cpp.o

Equipment/src/EquipmentDecorator.i: Equipment/src/EquipmentDecorator.cpp.i

.PHONY : Equipment/src/EquipmentDecorator.i

# target to preprocess a source file
Equipment/src/EquipmentDecorator.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/EquipmentDecorator.cpp.i
.PHONY : Equipment/src/EquipmentDecorator.cpp.i

Equipment/src/EquipmentDecorator.s: Equipment/src/EquipmentDecorator.cpp.s

.PHONY : Equipment/src/EquipmentDecorator.s

# target to generate assembly for a file
Equipment/src/EquipmentDecorator.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/EquipmentDecorator.cpp.s
.PHONY : Equipment/src/EquipmentDecorator.cpp.s

Equipment/src/Flimsy.o: Equipment/src/Flimsy.cpp.o

.PHONY : Equipment/src/Flimsy.o

# target to build an object file
Equipment/src/Flimsy.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Flimsy.cpp.o
.PHONY : Equipment/src/Flimsy.cpp.o

Equipment/src/Flimsy.i: Equipment/src/Flimsy.cpp.i

.PHONY : Equipment/src/Flimsy.i

# target to preprocess a source file
Equipment/src/Flimsy.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Flimsy.cpp.i
.PHONY : Equipment/src/Flimsy.cpp.i

Equipment/src/Flimsy.s: Equipment/src/Flimsy.cpp.s

.PHONY : Equipment/src/Flimsy.s

# target to generate assembly for a file
Equipment/src/Flimsy.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Flimsy.cpp.s
.PHONY : Equipment/src/Flimsy.cpp.s

Equipment/src/Mighty.o: Equipment/src/Mighty.cpp.o

.PHONY : Equipment/src/Mighty.o

# target to build an object file
Equipment/src/Mighty.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Mighty.cpp.o
.PHONY : Equipment/src/Mighty.cpp.o

Equipment/src/Mighty.i: Equipment/src/Mighty.cpp.i

.PHONY : Equipment/src/Mighty.i

# target to preprocess a source file
Equipment/src/Mighty.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Mighty.cpp.i
.PHONY : Equipment/src/Mighty.cpp.i

Equipment/src/Mighty.s: Equipment/src/Mighty.cpp.s

.PHONY : Equipment/src/Mighty.s

# target to generate assembly for a file
Equipment/src/Mighty.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Mighty.cpp.s
.PHONY : Equipment/src/Mighty.cpp.s

Equipment/src/Sword.o: Equipment/src/Sword.cpp.o

.PHONY : Equipment/src/Sword.o

# target to build an object file
Equipment/src/Sword.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Sword.cpp.o
.PHONY : Equipment/src/Sword.cpp.o

Equipment/src/Sword.i: Equipment/src/Sword.cpp.i

.PHONY : Equipment/src/Sword.i

# target to preprocess a source file
Equipment/src/Sword.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Sword.cpp.i
.PHONY : Equipment/src/Sword.cpp.i

Equipment/src/Sword.s: Equipment/src/Sword.cpp.s

.PHONY : Equipment/src/Sword.s

# target to generate assembly for a file
Equipment/src/Sword.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Equipment/src/Sword.cpp.s
.PHONY : Equipment/src/Sword.cpp.s

FileRead/fileReader.o: FileRead/fileReader.cpp.o

.PHONY : FileRead/fileReader.o

# target to build an object file
FileRead/fileReader.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/FileRead/fileReader.cpp.o
.PHONY : FileRead/fileReader.cpp.o

FileRead/fileReader.i: FileRead/fileReader.cpp.i

.PHONY : FileRead/fileReader.i

# target to preprocess a source file
FileRead/fileReader.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/FileRead/fileReader.cpp.i
.PHONY : FileRead/fileReader.cpp.i

FileRead/fileReader.s: FileRead/fileReader.cpp.s

.PHONY : FileRead/fileReader.s

# target to generate assembly for a file
FileRead/fileReader.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/FileRead/fileReader.cpp.s
.PHONY : FileRead/fileReader.cpp.s

GameBoard/gameBoard.o: GameBoard/gameBoard.cpp.o

.PHONY : GameBoard/gameBoard.o

# target to build an object file
GameBoard/gameBoard.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/GameBoard/gameBoard.cpp.o
.PHONY : GameBoard/gameBoard.cpp.o

GameBoard/gameBoard.i: GameBoard/gameBoard.cpp.i

.PHONY : GameBoard/gameBoard.i

# target to preprocess a source file
GameBoard/gameBoard.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/GameBoard/gameBoard.cpp.i
.PHONY : GameBoard/gameBoard.cpp.i

GameBoard/gameBoard.s: GameBoard/gameBoard.cpp.s

.PHONY : GameBoard/gameBoard.s

# target to generate assembly for a file
GameBoard/gameBoard.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/GameBoard/gameBoard.cpp.s
.PHONY : GameBoard/gameBoard.cpp.s

Graphics/src/actionGui.o: Graphics/src/actionGui.cpp.o

.PHONY : Graphics/src/actionGui.o

# target to build an object file
Graphics/src/actionGui.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/actionGui.cpp.o
.PHONY : Graphics/src/actionGui.cpp.o

Graphics/src/actionGui.i: Graphics/src/actionGui.cpp.i

.PHONY : Graphics/src/actionGui.i

# target to preprocess a source file
Graphics/src/actionGui.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/actionGui.cpp.i
.PHONY : Graphics/src/actionGui.cpp.i

Graphics/src/actionGui.s: Graphics/src/actionGui.cpp.s

.PHONY : Graphics/src/actionGui.s

# target to generate assembly for a file
Graphics/src/actionGui.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/actionGui.cpp.s
.PHONY : Graphics/src/actionGui.cpp.s

Graphics/src/graphics.o: Graphics/src/graphics.cpp.o

.PHONY : Graphics/src/graphics.o

# target to build an object file
Graphics/src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/graphics.cpp.o
.PHONY : Graphics/src/graphics.cpp.o

Graphics/src/graphics.i: Graphics/src/graphics.cpp.i

.PHONY : Graphics/src/graphics.i

# target to preprocess a source file
Graphics/src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/graphics.cpp.i
.PHONY : Graphics/src/graphics.cpp.i

Graphics/src/graphics.s: Graphics/src/graphics.cpp.s

.PHONY : Graphics/src/graphics.s

# target to generate assembly for a file
Graphics/src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/graphics.cpp.s
.PHONY : Graphics/src/graphics.cpp.s

Graphics/src/imagesGui.o: Graphics/src/imagesGui.cpp.o

.PHONY : Graphics/src/imagesGui.o

# target to build an object file
Graphics/src/imagesGui.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/imagesGui.cpp.o
.PHONY : Graphics/src/imagesGui.cpp.o

Graphics/src/imagesGui.i: Graphics/src/imagesGui.cpp.i

.PHONY : Graphics/src/imagesGui.i

# target to preprocess a source file
Graphics/src/imagesGui.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/imagesGui.cpp.i
.PHONY : Graphics/src/imagesGui.cpp.i

Graphics/src/imagesGui.s: Graphics/src/imagesGui.cpp.s

.PHONY : Graphics/src/imagesGui.s

# target to generate assembly for a file
Graphics/src/imagesGui.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/imagesGui.cpp.s
.PHONY : Graphics/src/imagesGui.cpp.s

Graphics/src/textGui.o: Graphics/src/textGui.cpp.o

.PHONY : Graphics/src/textGui.o

# target to build an object file
Graphics/src/textGui.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/textGui.cpp.o
.PHONY : Graphics/src/textGui.cpp.o

Graphics/src/textGui.i: Graphics/src/textGui.cpp.i

.PHONY : Graphics/src/textGui.i

# target to preprocess a source file
Graphics/src/textGui.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/textGui.cpp.i
.PHONY : Graphics/src/textGui.cpp.i

Graphics/src/textGui.s: Graphics/src/textGui.cpp.s

.PHONY : Graphics/src/textGui.s

# target to generate assembly for a file
Graphics/src/textGui.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/textGui.cpp.s
.PHONY : Graphics/src/textGui.cpp.s

Graphics/src/windowGui.o: Graphics/src/windowGui.cpp.o

.PHONY : Graphics/src/windowGui.o

# target to build an object file
Graphics/src/windowGui.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/windowGui.cpp.o
.PHONY : Graphics/src/windowGui.cpp.o

Graphics/src/windowGui.i: Graphics/src/windowGui.cpp.i

.PHONY : Graphics/src/windowGui.i

# target to preprocess a source file
Graphics/src/windowGui.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/windowGui.cpp.i
.PHONY : Graphics/src/windowGui.cpp.i

Graphics/src/windowGui.s: Graphics/src/windowGui.cpp.s

.PHONY : Graphics/src/windowGui.s

# target to generate assembly for a file
Graphics/src/windowGui.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/windowGui.cpp.s
.PHONY : Graphics/src/windowGui.cpp.s

Graphics/src/worldGui.o: Graphics/src/worldGui.cpp.o

.PHONY : Graphics/src/worldGui.o

# target to build an object file
Graphics/src/worldGui.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/worldGui.cpp.o
.PHONY : Graphics/src/worldGui.cpp.o

Graphics/src/worldGui.i: Graphics/src/worldGui.cpp.i

.PHONY : Graphics/src/worldGui.i

# target to preprocess a source file
Graphics/src/worldGui.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/worldGui.cpp.i
.PHONY : Graphics/src/worldGui.cpp.i

Graphics/src/worldGui.s: Graphics/src/worldGui.cpp.s

.PHONY : Graphics/src/worldGui.s

# target to generate assembly for a file
Graphics/src/worldGui.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/Graphics/src/worldGui.cpp.s
.PHONY : Graphics/src/worldGui.cpp.s

PlayerController/playerController.o: PlayerController/playerController.cpp.o

.PHONY : PlayerController/playerController.o

# target to build an object file
PlayerController/playerController.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/PlayerController/playerController.cpp.o
.PHONY : PlayerController/playerController.cpp.o

PlayerController/playerController.i: PlayerController/playerController.cpp.i

.PHONY : PlayerController/playerController.i

# target to preprocess a source file
PlayerController/playerController.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/PlayerController/playerController.cpp.i
.PHONY : PlayerController/playerController.cpp.i

PlayerController/playerController.s: PlayerController/playerController.cpp.s

.PHONY : PlayerController/playerController.s

# target to generate assembly for a file
PlayerController/playerController.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/PlayerController/playerController.cpp.s
.PHONY : PlayerController/playerController.cpp.s

asciiRpg.o: asciiRpg.cpp.o

.PHONY : asciiRpg.o

# target to build an object file
asciiRpg.cpp.o:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/asciiRpg.cpp.o
.PHONY : asciiRpg.cpp.o

asciiRpg.i: asciiRpg.cpp.i

.PHONY : asciiRpg.i

# target to preprocess a source file
asciiRpg.cpp.i:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/asciiRpg.cpp.i
.PHONY : asciiRpg.cpp.i

asciiRpg.s: asciiRpg.cpp.s

.PHONY : asciiRpg.s

# target to generate assembly for a file
asciiRpg.cpp.s:
	$(MAKE) -f CMakeFiles/gameAsciiRpg.dir/build.make CMakeFiles/gameAsciiRpg.dir/asciiRpg.cpp.s
.PHONY : asciiRpg.cpp.s

test/unit_test.o: test/unit_test.cpp.o

.PHONY : test/unit_test.o

# target to build an object file
test/unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/runUnitTest.dir/build.make CMakeFiles/runUnitTest.dir/test/unit_test.cpp.o
.PHONY : test/unit_test.cpp.o

test/unit_test.i: test/unit_test.cpp.i

.PHONY : test/unit_test.i

# target to preprocess a source file
test/unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/runUnitTest.dir/build.make CMakeFiles/runUnitTest.dir/test/unit_test.cpp.i
.PHONY : test/unit_test.cpp.i

test/unit_test.s: test/unit_test.cpp.s

.PHONY : test/unit_test.s

# target to generate assembly for a file
test/unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/runUnitTest.dir/build.make CMakeFiles/runUnitTest.dir/test/unit_test.cpp.s
.PHONY : test/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... runUnitTest"
	@echo "... gameAsciiRpg"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... BattleVisitor/BattleVisitor.o"
	@echo "... BattleVisitor/BattleVisitor.i"
	@echo "... BattleVisitor/BattleVisitor.s"
	@echo "... Character/Character.o"
	@echo "... Character/Character.i"
	@echo "... Character/Character.s"
	@echo "... Equipment/src/Axe.o"
	@echo "... Equipment/src/Axe.i"
	@echo "... Equipment/src/Axe.s"
	@echo "... Equipment/src/Deadly.o"
	@echo "... Equipment/src/Deadly.i"
	@echo "... Equipment/src/Deadly.s"
	@echo "... Equipment/src/EquipmentDecorator.o"
	@echo "... Equipment/src/EquipmentDecorator.i"
	@echo "... Equipment/src/EquipmentDecorator.s"
	@echo "... Equipment/src/Flimsy.o"
	@echo "... Equipment/src/Flimsy.i"
	@echo "... Equipment/src/Flimsy.s"
	@echo "... Equipment/src/Mighty.o"
	@echo "... Equipment/src/Mighty.i"
	@echo "... Equipment/src/Mighty.s"
	@echo "... Equipment/src/Sword.o"
	@echo "... Equipment/src/Sword.i"
	@echo "... Equipment/src/Sword.s"
	@echo "... FileRead/fileReader.o"
	@echo "... FileRead/fileReader.i"
	@echo "... FileRead/fileReader.s"
	@echo "... GameBoard/gameBoard.o"
	@echo "... GameBoard/gameBoard.i"
	@echo "... GameBoard/gameBoard.s"
	@echo "... Graphics/src/actionGui.o"
	@echo "... Graphics/src/actionGui.i"
	@echo "... Graphics/src/actionGui.s"
	@echo "... Graphics/src/graphics.o"
	@echo "... Graphics/src/graphics.i"
	@echo "... Graphics/src/graphics.s"
	@echo "... Graphics/src/imagesGui.o"
	@echo "... Graphics/src/imagesGui.i"
	@echo "... Graphics/src/imagesGui.s"
	@echo "... Graphics/src/textGui.o"
	@echo "... Graphics/src/textGui.i"
	@echo "... Graphics/src/textGui.s"
	@echo "... Graphics/src/windowGui.o"
	@echo "... Graphics/src/windowGui.i"
	@echo "... Graphics/src/windowGui.s"
	@echo "... Graphics/src/worldGui.o"
	@echo "... Graphics/src/worldGui.i"
	@echo "... Graphics/src/worldGui.s"
	@echo "... PlayerController/playerController.o"
	@echo "... PlayerController/playerController.i"
	@echo "... PlayerController/playerController.s"
	@echo "... asciiRpg.o"
	@echo "... asciiRpg.i"
	@echo "... asciiRpg.s"
	@echo "... test/unit_test.o"
	@echo "... test/unit_test.i"
	@echo "... test/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

